# Test .NET artefacts
# See also:
# - https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET test

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    # windows image w/ .NET 10
    # see: https://github.com/actions/runner-images/blob/win25/20260413.84/images/windows/Windows2025-Readme.md
    runs-on: windows-2025
    steps:
    - name: Check out repo
      uses: actions/checkout@v6
    # not needed at the mo as the default on windows-2025 is .net 10
    # - name: Set up .NET 10
    #   uses: actions/setup-dotnet@v5
    #   with:
    #     dotnet-version: '10.0.x'
    - name: Show .NET setup
      run: dotnet --info
    - name: Run framework-dependent nice
      run: test/osx-arm64-to-win-x64/framework-dependent/nice.exe -n 10 dotnet --version
    - name: Run self-contained nice
      run: test/osx-arm64-to-win-x64/self-contained/nice.exe -n 10 dotnet --version
